### ISSUE TITLE
IndexingError: Too many indexers

### ISSUE THREAD

**Issue by hewgreen** [MaxHalford/prince#13] opened 2017-09-27 12:03 UTC
Using example code:

```
import pandas as pd
import prince

df = pd.read_csv('ogm.csv')
mca = prince.MCA(df, n_components=-1)
mca.plot_rows(show_points=True, show_labels=False, color_by='Position Al A', ellipse_fill=True)
```

Error:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    mca.plot_rows(show_points=True, show_labels=False, color_by='Position Al A', ellipse_fill=True)
  File "/Users/hewgreen/anaconda/lib/python3.6/site-packages/prince/mca.py", line 154, in plot_rows
    ellipse_fill=ellipse_fill
  File "/Users/hewgreen/anaconda/lib/python3.6/site-packages/prince/plot/mpl/pca.py", line 30, in row_principal_coordinates
    data = principal_coordinates.iloc[:, axes].copy() # Active rows
  File "/Users/hewgreen/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py", line 1325, in __getitem__
    return self._getitem_tuple(key)
  File "/Users/hewgreen/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py", line 1662, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/Users/hewgreen/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py", line 189, in _has_valid_tuple
    if not self._has_valid_type(k, i):
  File "/Users/hewgreen/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py", line 1599, in _has_valid_type
    return self._is_valid_list_like(key, axis)
  File "/Users/hewgreen/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py", line 1648, in _is_valid_list_like
    raise IndexingError('Too many indexers')
pandas.core.indexing.IndexingError: Too many indexers
```

I tried to find some details about how to fix myself to no avail. Many thanks in advance for your help.

Regards

hewgreen

**Comment by 8ballbb** [comment] 2017-10-24 14:19
I had a similar issue. Did you "pip install prince"? If so, try the prince version given with "pip install git+https://github.com/MaxHalford/Prince" instead.

**Comment by blu3r4y** [comment] 2017-12-26 10:05
That is probably a duplicate to #10, which was fixed in the repository already. However, the package version for `pip` on https://pypi.python.org/pypi/prince is not updated yet.

**Comment by aguinaldoabbj** [comment] 2018-02-08 00:35
I've installed the last dev version and the problem persists.

**Comment by blu3r4y** [comment] 2018-02-13 21:42
@aguinaldoabbj I just tried it and couldn't reproduce the error on the latest master branch.
Could you provide a minimum working example?

**Comment by aguinaldoabbj** [comment] 2018-02-14 12:12
Dear,

I first tried my data and then used your example data (ogm.csv
<https://github.com/MaxHalford/prince/blob/master/examples/data/ogm.csv>).
So, I gave up and started using R's Factominer/Factoextra with rpy2.
Anyway, I'm gonna try again with my data and post here the logs.

2018-02-13 18:42 GMT-03:00 Mario Kahlhofer <notifications@github.com>:

**Comment by zippyjg** [comment] 2018-02-28 20:03
Still getting this error even with the latest version of Prince

**Comment by blu3r4y** [comment] 2018-02-28 20:16
@zippyjg Could you provide the code snippet which raises the error?

**Comment by naoko** [comment] 2018-04-02 23:50
I see changes from `iloc` to `loc` did resolve one case of `Too many indexers` error.
I then installed the latest and now I'm getting this `Too many indexers` error.
This error occurs at line # 12 of this example https://github.com/MaxHalford/prince/blob/master/examples/mca-ogm.py

```
----> 1 mca.plot_rows(show_points=True, show_labels=False, color_by='Position Al A', ellipse_fill=True)

~/projects/notebooks/env/lib/python3.6/site-packages/prince/mca.py in plot_rows(self, axes, show_points, show_labels, color_by, ellipse_outline, ellipse_fill)

~/projects/notebooks/env/lib/python3.6/site-packages/prince/plot/mpl/pca.py in row_principal_coordinates(self, axes, principal_coordinates, supplementary_principal_coordinates, explained_inertia, show_points, show_labels, color_labels, ellipse_outline, ellipse_fill)

~/projects/notebooks/env/lib/python3.6/site-packages/pandas/core/indexing.py in __getitem__(self, key)
   1365             except (KeyError, IndexError):
   1366                 pass
-> 1367             return self._getitem_tuple(key)
   1368         else:
   1369             # we by definition only have the 0th axis

~/projects/notebooks/env/lib/python3.6/site-packages/pandas/core/indexing.py in _getitem_tuple(self, tup)
   1735     def _getitem_tuple(self, tup):
   1736 
-> 1737         self._has_valid_tuple(tup)
   1738         try:
   1739             return self._getitem_lowerdim(tup)

~/projects/notebooks/env/lib/python3.6/site-packages/pandas/core/indexing.py in _has_valid_tuple(self, key)
    202             if i >= self.obj.ndim:
    203                 raise IndexingError('Too many indexers')
--> 204             if not self._has_valid_type(k, i):
    205                 raise ValueError("Location based indexing can only have "
    206                                  "[{types}] types"

~/projects/notebooks/env/lib/python3.6/site-packages/pandas/core/indexing.py in _has_valid_type(self, key, axis)
   1672             return self._is_valid_integer(key, axis)
   1673         elif is_list_like_indexer(key):
-> 1674             return self._is_valid_list_like(key, axis)
   1675         return False
   1676 

~/projects/notebooks/env/lib/python3.6/site-packages/pandas/core/indexing.py in _is_valid_list_like(self, key, axis)
   1721         # so don't treat a tuple as a valid indexer
   1722         if isinstance(key, tuple):
-> 1723             raise IndexingError('Too many indexers')
   1724 
   1725         # coerce the key to not exceed the maximum size of the index

IndexingError: Too many indexers
```

**Comment by blu3r4y** [comment] 2018-04-03 10:47
@naoko I couldn't reproduce the error on the latest master branch.

Are you sure that you installed prince directly from the repository?
`pip install git+https://github.com/MaxHalford/prince`

**Comment by naoko** [comment] 2018-04-03 14:28
My apologies. I re-installed the latest and example ran smoothly. Thank you for your quick response. All good. Finally thank you for your great work.

**Comment by blu3r4y** [comment] 2018-04-25 11:17
@cnorsig Please use `pip install git+https://github.com/MaxHalford/prince`,
not ~~`pip install git https://github.com/MaxHalford/prince`~~.

You forgot the `+` sign.

**Comment by MaxHalford** [comment] 2018-05-20 13:04
I'm closing this since there hasn't been any notice for a few weeks. Feel free to reopen the issue if you like.

**Closed by MaxHalford** 2018-05-20 13:04 UTC

**Comment by Sunil4423** [comment] 2020-02-07 17:51
IndexingError                             Traceback (most recent call last)
<ipython-input-4-d551835cc4a0> in <module>
      1 dataset=pd.read_csv("C:/Users/Vidyashree B R/Desktop/Machine Learning A-Z Template Folder/Part 9 - Dimensionality Reduction/Section 43 - Principal Component Analysis (PCA)/Wine.csv")
----> 2 X=dataset.iloc[:, 0,13 ].values
      3 Y=dataset.iloc[:, 13].values

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py in __getitem__(self, key)
   1492             except (KeyError, IndexError, AttributeError):
   1493                 pass
-> 1494             return self._getitem_tuple(key)
   1495         else:
   1496             # we by definition only have the 0th axis

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py in _getitem_tuple(self, tup)
   2141     def _getitem_tuple(self, tup):
   2142 
-> 2143         self._has_valid_tuple(tup)
   2144         try:
   2145             return self._getitem_lowerdim(tup)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py in _has_valid_tuple(self, key)
    219         for i, k in enumerate(key):
    220             if i >= self.obj.ndim:
--> 221                 raise IndexingError('Too many indexers')
    222             try:
    223                 self._validate_key(k, i)

IndexingError: Too many indexers

**Comment by Sunil4423** [comment] 2020-02-07 17:52
Please use pip install git+https://github.com/MaxHalford/prince this code is not working @blu3r4y

**Comment by MaxHalford** [comment] 2020-02-07 17:54
@Sunil4423 this issue is closed. If you have an error please open a new open and provided a minimum working example.

**Comment by blu3r4y** [comment] 2020-02-07 18:42
@Sunil4423 There is an error in your code on line 2 - not in prince. Re-investigate your stack trace.
