### ISSUE TITLE
FAMD implementation

### ISSUE THREAD

**Issue by thusithaC** [MaxHalford/prince#16] opened 2017-12-17 07:36 UTC
Hi,

Any updates on the FAMD? Trying to get some staticstical analysis work done using python, but unfortunately cant find many tools. Appreciate the effort you have put into this package though!

**Comment by mlisovyi** [comment] 2018-08-09 07:41
Is the FAMD implementation complete by now? It seems to be a high-level wrapper around MFA treating each feature as a separate group. While this seems to be reasonable for categorical features, what does it mean for numerical features?
PS Thanks a lot for developing this package! It is awesome to have these tools with convenient interface. I was not able to find another python package with FAMD implementation.

**Comment by MaxHalford** [comment] 2018-08-09 09:13
I'm pretty sure the implementation is wrong. Instead of using one group per variable I should be using I group for the numerical variables and one group for the categorical ones. I'll fix this ASAP.

No worries! It is a bit difficult to find reference implementations to compare with so sometimes I get things wrong. FactoMineR in R is nice but the source code is very difficult to read and there are barely any comments.

**Comment by mlisovyi** [comment] 2018-08-09 09:26
Indeed, there are packages in R, but I have 0 knowledge of R so far, unfortunately :(

I also bumped into GLRM approach, which is documented here: https://web.stanford.edu/~boyd/papers/glrm.html. The paper is long, but the main idea is that instead of eigenvector decomposition, they solve a minimisation problem with loss function being different for numerical and categorical features. They also python, Julia and Spark implementations. The native python implementation is not advised to be used on medium or large datasets (I think, they mention O(100x100), but one should look it up in the paper). But there is a python wrapper around the Julia implementation available here: https://github.com/udellgroup/pyglrm, which is claimed to be able to work on large (in-memory) datasets. I do not have hands-on experience with it, but maybe it would be useful for you.

**Comment by MaxHalford** [comment] 2018-08-09 09:32
Okay the implementation should be good in version 0.4.5. I'll close this issue once everyone seems happy with it and once I've added some more documentation.

Thanks for paper, I didn't know about this.

**Comment by Arne-He** [comment] 2018-08-19 16:36
Hi,

what is the intended behaviour on Datasets containing Zero Rows? 
If I run FAMD on a mixed dataset like the one below (based on the doku) it crashes.

```
...
data=[
         ['A', 'A', 'A', 2, 5, 7, 0, 3, 6, 7],
         ['A', 'A', 'A', 4, 4, 4, 0, 4, 4, 3],
         ['B', 'A', 'B', 5, 2, 1, 0, 7, 1, 1],
         ['B', 'A', 'B', 7, 2, 1, 0, 2, 2, 2],
         ['B', 'B', 'B', 3, 5, 6, 0, 2, 6, 6],
         ['B', 'B', 'A', 3, 5, 4, 0, 1, 7, 5]
     ],
...
```

**Comment by Arne-He** [comment] 2018-08-20 20:04
Thanks for the quick reply and fix!

**Comment by srinikprem** [comment] 2018-09-20 06:48
Hi,

How can we determine the variance explained by all original variable in a given famd component?

**Comment by MaxHalford** [comment] 2018-09-20 11:05
Hey @srinikprem,

This hasn't been implemented yet, I'm sorry.

By the way I'm going to close this issue because it seems to be going stale. Feel free to open others if you have questions/bugs? I'm swamped at the moment but I plan to get back to `prince` and implement some more stuff. Please try to be precise in your demands.

**Closed by MaxHalford** 2018-09-20 11:05 UTC
